import type { PdfThemePack } from '../theme-pack';

export const toonGammaThemePack: PdfThemePack = {
  id: 'toon-gamma',
  name: 'TOON Gamma',
  description:
    'Theme derived from the March 2026 TOON institutional report: warm stone background, navy research panels, beige compliance/footer bands, and compact editorial tables.',
  palette: {
    pageBg: '#F4F2EE',
    pageAltBg: '#FFFFFF',
    heroBg: '#0B2347',
    heroText: '#F8FAFC',
    cardBg: '#FFFFFF',
    cardAltBg: '#F8FAFC',
    softPanelBg: '#E7DFC7',
    footerBg: '#E7DFC7',
    border: '#D8DCE5',
    borderStrong: '#BCC5D3',
    text: '#132238',
    textMuted: '#3B4A60',
    textSoft: '#6B7280',
    heading: '#0F2340',
    accent: '#0B2347',
    accentSoft: '#E8EEF8',
    gold: '#B69544',
    goldSoft: '#F3EACF',
    positive: '#117A65',
    positiveSoft: '#D9F5EE',
    negative: '#B42318',
    negativeSoft: '#FEE4E2',
    warning: '#B7791F',
    warningSoft: '#FEF3C7',
    neutral: '#526077',
    neutralSoft: '#ECEFF3',
  },
  typography: {
    fontFamily: 'Helvetica',
    headingFamily: 'Helvetica-Bold',
    boldFamily: 'Helvetica-Bold',
    h1: 27,
    h2: 18,
    h3: 13,
    h4: 10.5,
    body: 9.8,
    bodySmall: 8.8,
    label: 7.5,
    caption: 6.8,
    lineHeight: 1.42,
  },
  spacing: {
    pagePaddingX: 30,
    pagePaddingY: 24,
    sectionGap: 14,
    blockGap: 9,
    cardPadding: 11,
    tableCellX: 7,
    tableCellY: 5,
    radiusSm: 3,
    radiusMd: 8,
    radiusLg: 14,
  },
  cover: {
    align: 'left',
    titleCase: 'normal',
    titleTracking: 0.1,
    useSplitHero: true,
    useMetaCards: true,
  },
  table: {
    striped: true,
    dense: true,
    headerUppercase: true,
  },
  score: {
    bullishThreshold: 72,
    bearishThreshold: 42,
  },
};
