import { sql } from "@/lib/db";

type SeedSecurity = {
  id: string;
  symbol: string;
  companyName: string;
  normalizedCompanyName: string;
  exchange: string;
  primaryExchange: string;
  region: string;
  isActive: boolean;
  isin: string | null;
  figi: string | null;
  country: string;
  currency: string;
  securityType: string;
  sector: string;
  industry: string;
};

const SEED_SECURITIES: SeedSecurity[] = [
  {
    id: "sec_aapl",
    symbol: "AAPL",
    companyName: "Apple Inc.",
    normalizedCompanyName: "apple",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Consumer Electronics",
  },
  {
    id: "sec_msft",
    symbol: "MSFT",
    companyName: "Microsoft Corporation",
    normalizedCompanyName: "microsoft",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Software",
  },
  {
    id: "sec_nvda",
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    normalizedCompanyName: "nvidia",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Semiconductors",
  },
  {
    id: "sec_googl",
    symbol: "GOOGL",
    companyName: "Alphabet Inc.",
    normalizedCompanyName: "alphabet",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Communication Services",
    industry: "Internet Content & Information",
  },
  {
    id: "sec_amzn",
    symbol: "AMZN",
    companyName: "Amazon.com, Inc.",
    normalizedCompanyName: "amazon com",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
  },
  {
    id: "sec_meta",
    symbol: "META",
    companyName: "Meta Platforms, Inc.",
    normalizedCompanyName: "meta platforms",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Communication Services",
    industry: "Internet Content & Information",
  },
  {
    id: "sec_tsla",
    symbol: "TSLA",
    companyName: "Tesla, Inc.",
    normalizedCompanyName: "tesla",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
  },
  {
    id: "sec_brkb",
    symbol: "BRK.B",
    companyName: "Berkshire Hathaway Inc.",
    normalizedCompanyName: "berkshire hathaway",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Insurance - Diversified",
  },
  {
    id: "sec_jpm",
    symbol: "JPM",
    companyName: "JPMorgan Chase & Co.",
    normalizedCompanyName: "jpmorgan chase co",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Banks - Diversified",
  },
  {
    id: "sec_v",
    symbol: "V",
    companyName: "Visa Inc.",
    normalizedCompanyName: "visa",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Credit Services",
  },
  {
    id: "sec_ma",
    symbol: "MA",
    companyName: "Mastercard Incorporated",
    normalizedCompanyName: "mastercard",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Credit Services",
  },
  {
    id: "sec_xom",
    symbol: "XOM",
    companyName: "Exxon Mobil Corporation",
    normalizedCompanyName: "exxon mobil",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_cvx",
    symbol: "CVX",
    companyName: "Chevron Corporation",
    normalizedCompanyName: "chevron",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_ko",
    symbol: "KO",
    companyName: "The Coca-Cola Company",
    normalizedCompanyName: "the coca cola company",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
  },
  {
    id: "sec_pep",
    symbol: "PEP",
    companyName: "PepsiCo, Inc.",
    normalizedCompanyName: "pepsico",
    exchange: "NASDAQ",
    primaryExchange: "NASDAQ",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
  },
  {
    id: "sec_unh",
    symbol: "UNH",
    companyName: "UnitedHealth Group Incorporated",
    normalizedCompanyName: "unitedhealth group",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Healthcare Plans",
  },
  {
    id: "sec_jnj",
    symbol: "JNJ",
    companyName: "Johnson & Johnson",
    normalizedCompanyName: "johnson johnson",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_pfe",
    symbol: "PFE",
    companyName: "Pfizer Inc.",
    normalizedCompanyName: "pfizer",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_lly",
    symbol: "LLY",
    companyName: "Eli Lilly and Company",
    normalizedCompanyName: "eli lilly and company",
    exchange: "NYSE",
    primaryExchange: "NYSE",
    region: "North America",
    isActive: true,
    isin: null,
    figi: null,
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
];

async function seedSecurities(): Promise<void> {
  // Ensure search_path is set to public schema
  await sql.unsafe(`SET search_path TO public`, []);

  for (const security of SEED_SECURITIES) {
    await sql.unsafe(
      `
        INSERT INTO securities (
          id,
          symbol,
          company_name,
          normalized_company_name,
          exchange,
          primary_exchange,
          region,
          is_active,
          isin,
          figi,
          country,
          currency,
          security_type,
          sector,
          industry,
          created_at,
          updated_at
        )
        VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,NOW(),NOW()
        )
        ON CONFLICT (id)
        DO UPDATE SET
          symbol = EXCLUDED.symbol,
          company_name = EXCLUDED.company_name,
          normalized_company_name = EXCLUDED.normalized_company_name,
          exchange = EXCLUDED.exchange,
          primary_exchange = EXCLUDED.primary_exchange,
          region = EXCLUDED.region,
          is_active = EXCLUDED.is_active,
          isin = EXCLUDED.isin,
          figi = EXCLUDED.figi,
          country = EXCLUDED.country,
          currency = EXCLUDED.currency,
          security_type = EXCLUDED.security_type,
          sector = EXCLUDED.sector,
          industry = EXCLUDED.industry,
          updated_at = NOW()
      `,
      [
        security.id,
        security.symbol,
        security.companyName,
        security.normalizedCompanyName,
        security.exchange,
        security.primaryExchange,
        security.region,
        security.isActive,
        security.isin,
        security.figi,
        security.country,
        security.currency,
        security.securityType,
        security.sector,
        security.industry,
      ],
    );
  }

  const result = await sql.unsafe<Array<{ count: number | string }>>(
    `SELECT COUNT(*)::int AS count FROM securities`,
    [],
  );

  console.log(
    `Seed complete. securities count = ${String(result[0]?.count ?? 0)}`,
  );
}

seedSecurities()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error("Failed to seed securities", error);
    process.exit(1);
  });
