import { sql } from "@/lib/db";

type SeedSecurity = {
  id: string;
  symbol: string;
  companyName: string;
  exchange: string;
  country: string;
  currency: string;
  securityType: string;
  sector: string;
  industry: string;
};

const SEED_SECURITIES: SeedSecurity[] = [
  {
    id: "sec_aapl",
    symbol: "AAPL",
    companyName: "Apple Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Consumer Electronics",
  },
  {
    id: "sec_msft",
    symbol: "MSFT",
    companyName: "Microsoft Corporation",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Software",
  },
  {
    id: "sec_nvda",
    symbol: "NVDA",
    companyName: "NVIDIA Corporation",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Semiconductors",
  },
  {
    id: "sec_googl",
    symbol: "GOOGL",
    companyName: "Alphabet Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Communication Services",
    industry: "Internet Content & Information",
  },
  {
    id: "sec_amzn",
    symbol: "AMZN",
    companyName: "Amazon.com, Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
  },
  {
    id: "sec_meta",
    symbol: "META",
    companyName: "Meta Platforms, Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Communication Services",
    industry: "Internet Content & Information",
  },
  {
    id: "sec_tsla",
    symbol: "TSLA",
    companyName: "Tesla, Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
  },
  {
    id: "sec_brkb",
    symbol: "BRK.B",
    companyName: "Berkshire Hathaway Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Insurance - Diversified",
  },
  {
    id: "sec_jpm",
    symbol: "JPM",
    companyName: "JPMorgan Chase & Co.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Banks - Diversified",
  },
  {
    id: "sec_v",
    symbol: "V",
    companyName: "Visa Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Credit Services",
  },
  {
    id: "sec_ma",
    symbol: "MA",
    companyName: "Mastercard Incorporated",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Credit Services",
  },
  {
    id: "sec_xom",
    symbol: "XOM",
    companyName: "Exxon Mobil Corporation",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_cvx",
    symbol: "CVX",
    companyName: "Chevron Corporation",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_ko",
    symbol: "KO",
    companyName: "The Coca-Cola Company",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
  },
  {
    id: "sec_pep",
    symbol: "PEP",
    companyName: "PepsiCo, Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
  },
  {
    id: "sec_unh",
    symbol: "UNH",
    companyName: "UnitedHealth Group Incorporated",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Healthcare Plans",
  },
  {
    id: "sec_jnj",
    symbol: "JNJ",
    companyName: "Johnson & Johnson",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_pfe",
    symbol: "PFE",
    companyName: "Pfizer Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_ll y",
    symbol: "LLY",
    companyName: "Eli Lilly and Company",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_hd",
    symbol: "HD",
    companyName: "The Home Depot, Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Home Improvement Retail",
  },
  {
    id: "sec_cost",
    symbol: "COST",
    companyName: "Costco Wholesale Corporation",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
  },
  {
    id: "sec_wmt",
    symbol: "WMT",
    companyName: "Walmart Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
  },
  {
    id: "sec_orcl",
    symbol: "ORCL",
    companyName: "Oracle Corporation",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Software - Infrastructure",
  },
  {
    id: "sec_adbe",
    symbol: "ADBE",
    companyName: "Adobe Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Software",
  },
  {
    id: "sec_csco",
    symbol: "CSCO",
    companyName: "Cisco Systems, Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Communication Equipment",
  },
  {
    id: "sec_avgo",
    symbol: "AVGO",
    companyName: "Broadcom Inc.",
    exchange: "NASDAQ",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Semiconductors",
  },
  {
    id: "sec_tsm",
    symbol: "TSM",
    companyName: "Taiwan Semiconductor Manufacturing Company Limited",
    exchange: "NYSE",
    country: "Taiwan",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Semiconductors",
  },
  {
    id: "sec_sap",
    symbol: "SAP",
    companyName: "SAP SE",
    exchange: "NYSE",
    country: "Germany",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Software",
  },
  {
    id: "sec_asml",
    symbol: "ASML",
    companyName: "ASML Holding N.V.",
    exchange: "NASDAQ",
    country: "Netherlands",
    currency: "USD",
    securityType: "Equity",
    sector: "Technology",
    industry: "Semiconductor Equipment & Materials",
  },
  {
    id: "sec_nvs",
    symbol: "NVS",
    companyName: "Novartis AG",
    exchange: "NYSE",
    country: "Switzerland",
    currency: "USD",
    securityType: "Equity",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
  },
  {
    id: "sec_ul",
    symbol: "UL",
    companyName: "Unilever PLC",
    exchange: "NYSE",
    country: "United Kingdom",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
  },
  {
    id: "sec_baba",
    symbol: "BABA",
    companyName: "Alibaba Group Holding Limited",
    exchange: "NYSE",
    country: "China",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
  },
  {
    id: "sec_tencent",
    symbol: "TCEHY",
    companyName: "Tencent Holdings Limited",
    exchange: "OTC",
    country: "China",
    currency: "USD",
    securityType: "Equity",
    sector: "Communication Services",
    industry: "Internet Content & Information",
  },
  {
    id: "sec_sony",
    symbol: "SONY",
    companyName: "Sony Group Corporation",
    exchange: "NYSE",
    country: "Japan",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Consumer Electronics",
  },
  {
    id: "sec_tm",
    symbol: "TM",
    companyName: "Toyota Motor Corporation",
    exchange: "NYSE",
    country: "Japan",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
  },
  {
    id: "sec_nsany",
    symbol: "NSANY",
    companyName: "Nissan Motor Co., Ltd.",
    exchange: "OTC",
    country: "Japan",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
  },
  {
    id: "sec_shel",
    symbol: "SHEL",
    companyName: "Shell plc",
    exchange: "NYSE",
    country: "United Kingdom",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_tte",
    symbol: "TTE",
    companyName: "TotalEnergies SE",
    exchange: "NYSE",
    country: "France",
    currency: "USD",
    securityType: "Equity",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
  },
  {
    id: "sec_bac",
    symbol: "BAC",
    companyName: "Bank of America Corporation",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Banks - Diversified",
  },
  {
    id: "sec_c",
    symbol: "C",
    companyName: "Citigroup Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Banks - Diversified",
  },
  {
    id: "sec_gs",
    symbol: "GS",
    companyName: "The Goldman Sachs Group, Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Capital Markets",
  },
  {
    id: "sec_ms",
    symbol: "MS",
    companyName: "Morgan Stanley",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Capital Markets",
  },
  {
    id: "sec_blk",
    symbol: "BLK",
    companyName: "BlackRock, Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Asset Management",
  },
  {
    id: "sec_spgi",
    symbol: "SPGI",
    companyName: "S&P Global Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Financial Services",
    industry: "Financial Data & Exchanges",
  },
  {
    id: "sec_mo",
    symbol: "MO",
    companyName: "Altria Group, Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Tobacco",
  },
  {
    id: "sec_pg",
    symbol: "PG",
    companyName: "The Procter & Gamble Company",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
  },
  {
    id: "sec_mcd",
    symbol: "MCD",
    companyName: "McDonald's Corporation",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
  },
  {
    id: "sec_nke",
    symbol: "NKE",
    companyName: "NIKE, Inc.",
    exchange: "NYSE",
    country: "United States",
    currency: "USD",
    securityType: "Equity",
    sector: "Consumer Discretionary",
    industry: "Footwear & Accessories",
  },
];

async function seedSecurities(): Promise<void> {
  for (const security of SEED_SECURITIES) {
    await sql.unsafe(
      `
        INSERT INTO securities (
          id,
          symbol,
          company_name,
          exchange,
          country,
          currency,
          security_type,
          sector,
          industry,
          created_at,
          updated_at
        )
        VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
        )
        ON CONFLICT (id)
        DO UPDATE SET
          symbol = EXCLUDED.symbol,
          company_name = EXCLUDED.company_name,
          exchange = EXCLUDED.exchange,
          country = EXCLUDED.country,
          currency = EXCLUDED.currency,
          security_type = EXCLUDED.security_type,
          sector = EXCLUDED.sector,
          industry = EXCLUDED.industry,
          updated_at = NOW()
      `,
      [
        security.id,
        security.symbol,
        security.companyName,
        security.exchange,
        security.country,
        security.currency,
        security.securityType,
        security.sector,
        security.industry,
      ],
    );
  }

  const result = await sql.unsafe<Array<{ count: number | string }>>(
    `
      SELECT COUNT(*)::int AS count
      FROM securities
    `,
    [],
  );

  console.log(`Seed complete. securities count = ${String(result[0]?.count ?? 0)}`);
}

seedSecurities()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error("Failed to seed securities", error);
    process.exit(1);
  });
